### DISCUSSION TITLE
Global Server State

### DISCUSSION THREAD

**Discussion by goldenratio** [spinframework/spin#2381] [General]
is it possible to have a shared global app state (thread safe), so this data is accessible in components (read/write). Something similar to actix-web's app_data.

**Comment by lann** [comment]
You can configure the [Spin key-value store](https://developer.fermyon.com/spin/v2/kv-store-api-guide) to run in-memory:


```toml
# runtime_config.toml
[key_value_store.default]
type = "spin"
# By omitting the path below, the store will exist only in memory
# path = "path/to/store.d"
```

```console
$ spin up --runtime-config-file runtime_config.toml
...
Using in-memory default key-value store; data will not be saved!
```

**Reply by goldenratio** [reply]
can it be more than KV data, something like game play manager (fancy struct with impl) (in-memory). I don't want to create additional service for this

**Reply by lann** [reply]
You can similarly configure in-memory [SQLite Storage](https://developer.fermyon.com/spin/v2/sqlite-api-guide):

```toml
[sqlite_database.default]
type = "spin"
```

Those are the only two in-memory options currently available with Spin.
