### ISSUE TITLE
Use `.cargo/config.toml` `target = "wasm32-wasi"` in test crates

### ISSUE THREAD

**Issue by lann** [spinframework/spin#234]
Some quick testing suggests that a [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file like this:

```toml
[toolchain]
targets = [ "wasm32-wasi" ]
```

will make `cargo` default to `--target wasm32-wasi`
