### ISSUE TITLE
Add escape syntax to variables expansion syntax (`spin-expressions`)

### ISSUE THREAD

**Issue by lann** [spinframework/spin#2528]
The current Mustache-inspired template syntax has no way of escaping double open quotes (`{{`).

While no one has complained about this yet (loudly enough for me to hear), we should probably proactively fix this as it would technically introduce a breaking change.

Some options:

- `\` escaping. Annoyingly, this would require double-backslash in TOML, but given the evident rarity of needing this maybe that is fine.
  ```toml
  var1 = "\\{{ not interpolated }}"
  var2 = "one backslash: \\\\" # 😬
  ```
- Some kind of quoted literal in braces, like Go templates:
  ```toml
  var1 = "{{`{{`}} not interpolated }}"
  # or
  var1 = "{{`{{ not interpolated }}`}}"
  ```

Other suggestions welcome.
