### ISSUE TITLE
Is it possible to allow write access to a mounted directory?

### ISSUE THREAD

**Issue by k0pernicus** [spinframework/spin#3018]
Hi,

In my spin app I allowed access to a full local directory, like this, mentioned in the file server example:
```toml
[component.my_file_storage]
...
files = [{ source="storage_directory", destination="/" }]
```

Reading files from this directory is fine: it finds the files, I can open them and stream the content.
However I wanted to create some files or directories from the spin app to my local directory, which is not possible at this stage (leads to an "Operation not permitted" os error).

It seems that `files` is read-only, as stated in this issue: https://github.com/spinframework/spin/issues/605.
But is it possible to change the permissions to read & write?

It seems `allow_transient_writes` is not allowed anymore, and I did not find anything relevant in the documentation unfortunately.

Thanks in advance
