### ISSUE TITLE
Push a local application configuration to Bindle

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin#37]
A local Spin application configuration is a file that contains information about the application and its components:

```toml
name        = "spin-hello-world"
version     = "1.0.0"
description = "A simple application that returns hello and goodbye."
authors     = [ "Radu Matei <radu@fermyon.com>" ]
trigger     = "http"

[[component]]
    source = "target/wasm32-wasi/release/spinhelloworld.wasm"
    id     = "hello"
    files = [ ...]
    env = [ ...]
[component.trigger]
    route = "/hello"
```
See https://github.com/fermyon/spin/blob/main/docs/configuration.md#configuration-for-spin-applications.

There should be a way to package the application defined by the configuration as a bindle, distribute it, then run it based on its remote reference.
