### ISSUE TITLE
Request URI passed into a Spin HTTP component should be stripped of the route

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin#72]
Currently, when a component's declared route matches a request, the request's full URI is passed as the component's URI.

To illustrate, take the following component:

```toml
[[component]]
id = "foo"
[component.trigger]
route = "/static/..."
```

Assuming Spin is listening on `example.com`, a request to `example.com/static/images/image.png` is currently translated into the component with the full `/static/images/image.png` URI.

I think the expected behavior should be that the URI that reaches the component to be stripped of the initial mapped route, so in this case it should be `/images/image.png`.
